name: Build README

on:
  workflow_dispatch:
  schedule:
  - cron: "30 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 
    - name: Install dependencies
      run: pip install requests 
    - name: Update readme
      run: python update-readme.py
      env: 
      BLOG_INDEX_URL: "https://github.com/imsorx/blog/raw/main/index.json"
      BLOG_BASE_URL: "https://sorx.space/blog/"
    - name: Commit and push
      run: |-
        git diff
        git config --global user.email "42103905+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "BOT"
        git commit -am "Updated posts"
        git push
